# Locust Configuration File
# ------------------------------------

# Target host (Kubernetes Ingress on Port 80, or API Gateway / Docker on http://localhost:8000 or http://localhost:80)
host = http://localhost

# Web UI settings
web-host = 0.0.0.0
web-port = 8089

# Default simulation parameters
users = 50
spawn-rate = 5
run-time = 2m

# locustfile location
locustfile = locustfile.py

# Headless mode options (uncomment when running in CI/CD or automated pipelines):
# headless = true
# html = locust_report.html
# csv = locust_stats
