apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: prod
spec:

  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: sumithsraikar/e-commerce-devops-project:search-service-v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: search-service
  ports:
    - port: 5002
      targetPort: 5002
      protocol: TCP


